fix of strange new bug
without this, I got errors trying to make a request to '' (empty url)
```
    raise ValueError(f"Missing scheme in request url: {self._url}")
ValueError: Missing scheme in request url:
```
idk why and how this was introduced, core logic of extracting `loc` is the same I believe