Update file_path() example in media-pipeline.rst
`def file_path(self, request, response, info):` throws error `Failure instance: Traceback (failure with no frames): <class 'TypeError'>: file_path() missing 1 required positional argument: 'response'` under item_completed() results. Setting default arguments fixes the issue.